//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W1986411.EAD.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FitnessTrackingRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FitnessTrackingRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("W1986411.EAD.Service.FitnessTrackingRes", typeof(FitnessTrackingRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat meal plan creation failed..
        /// </summary>
        internal static string Message_CheatMealPlanCreatedFailed {
            get {
                return ResourceManager.GetString("Message_CheatMealPlanCreatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat meal plan creation successful..
        /// </summary>
        internal static string Message_CheatMealPlanCreatedSuccess {
            get {
                return ResourceManager.GetString("Message_CheatMealPlanCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat meal plan remove failed..
        /// </summary>
        internal static string Message_CheatMealPlanRemoveFailed {
            get {
                return ResourceManager.GetString("Message_CheatMealPlanRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat meal plan remove successful..
        /// </summary>
        internal static string Message_CheatMealPlanRemoveSuccess {
            get {
                return ResourceManager.GetString("Message_CheatMealPlanRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat meal plan retrieve failed..
        /// </summary>
        internal static string Message_CheatMealPlanRetrieveFailed {
            get {
                return ResourceManager.GetString("Message_CheatMealPlanRetrieveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat meal plan update failed..
        /// </summary>
        internal static string Message_CheatMealPlanUpdatedFailed {
            get {
                return ResourceManager.GetString("Message_CheatMealPlanUpdatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat meal plan update successful..
        /// </summary>
        internal static string Message_CheatMealPlanUpdatedSuccess {
            get {
                return ResourceManager.GetString("Message_CheatMealPlanUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login user credentials invalid..
        /// </summary>
        internal static string Message_UserLoginCredentialsInvalid {
            get {
                return ResourceManager.GetString("Message_UserLoginCredentialsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration failed..
        /// </summary>
        internal static string Message_UserRegistrationFailed {
            get {
                return ResourceManager.GetString("Message_UserRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration successful..
        /// </summary>
        internal static string Message_UserRegistrationSuccess {
            get {
                return ResourceManager.GetString("Message_UserRegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan creation failed..
        /// </summary>
        internal static string Message_WorkoutPlanCreatedFailed {
            get {
                return ResourceManager.GetString("Message_WorkoutPlanCreatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan creation successful..
        /// </summary>
        internal static string Message_WorkoutPlanCreatedSuccess {
            get {
                return ResourceManager.GetString("Message_WorkoutPlanCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan remove failed..
        /// </summary>
        internal static string Message_WorkoutPlanRemoveFailed {
            get {
                return ResourceManager.GetString("Message_WorkoutPlanRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan remove successful..
        /// </summary>
        internal static string Message_WorkoutPlanRemoveSuccess {
            get {
                return ResourceManager.GetString("Message_WorkoutPlanRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan retrieve failed..
        /// </summary>
        internal static string Message_WorkoutPlanRetrieveFailed {
            get {
                return ResourceManager.GetString("Message_WorkoutPlanRetrieveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan update failed..
        /// </summary>
        internal static string Message_WorkoutPlanUpdatedFailed {
            get {
                return ResourceManager.GetString("Message_WorkoutPlanUpdatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout plan update successful..
        /// </summary>
        internal static string Message_WorkoutPlanUpdatedSuccess {
            get {
                return ResourceManager.GetString("Message_WorkoutPlanUpdatedSuccess", resourceCulture);
            }
        }
    }
}
